/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
    Float,
    Html,
    MeshReflectorMaterial,
    useGLTF
} from '@react-three/drei'
import {Chat} from "../chat/Chat.tsx";
import client from "../../../graphql";
import { ApolloProvider } from '@apollo/client';
import {useState} from "react";

export function Model() {
    const { nodes, materials } : any = useGLTF('/models/scifi-computer.glb')
    const [ isChatbotAngry, setIsChatbotAngry] = useState(false)
    return (

        <group scale={1} rotation={[0, Math.PI * 1.5, 0]} position={[0, 0, 0]} dispose={null}>
                <mesh position={[0,-1,0]}>
                        <planeGeometry/>
                        <MeshReflectorMaterial
                            blur={[0, 0]}
                            mixBlur={0}
                            mixStrength={1}
                            mixContrast={1}
                            resolution={256}
                            mirror={0}
                            depthScale={0}
                            minDepthThreshold={0.9}
                            maxDepthThreshold={1}
                            depthToBlurRatioBias={0.25}
                            distortion={1}
                            reflectorOffset={0.2}
                        />
                </mesh>
                <group position={[-0.015, 0.569, -3.102]} rotation={[0, -0.575, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_175.geometry}
                            material={materials.drivers}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_176.geometry}
                            material={materials.glass}
                        />
                </group>
                <group position={[-0.015, -0.23, -3.102]} rotation={[0, -0.575, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_178.geometry}
                            material={materials.drivers}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_179.geometry}
                            material={materials.glass}
                        />
                </group>
                <group position={[-0.015, 1.378, -3.102]} rotation={[0, -0.575, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_143.geometry}
                            material={materials.drivers}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_144.geometry}
                            material={materials.glass}
                        />
                </group>
                <group position={[-1.591, 0.745, 2.835]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_148.geometry}
                            material={materials.drivers}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_149.geometry}
                            material={materials.material_0}
                        />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_181.geometry}
                    material={materials.warm}
                    position={[-0.8, -0.53, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -0.579, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_43.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -0.986, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_45.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -1.406, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.643, -1.254, 4.582]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_49.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-3.703, -1.254, -4.253]}
                    rotation={[Math.PI, -1.227, Math.PI]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_67.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.931, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_69.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.931, -0.288]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_71.geometry}
                    material={materials.Cable_and_conectors}
                    position={[0.382, -0.007, 3.986]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_41.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -0.579, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_141.geometry}
                    material={materials.drivers}
                    position={[-0.991, 0.745, 2.835]}
                    rotation={[-0.014, -0.044, 1.677]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_73.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-1.009, 0.079, -1.507]}
                    rotation={[-0.179, -0.253, -0.045]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_183.geometry}
                    material={materials.glass}
                    position={[-2.87, 0.733, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_205.geometry}
                    material={materials.monitor_and_details}
                    position={[2.183, -1.019, 0.222]}
                    rotation={[0, 0, 0.151]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_207.geometry}
                    material={materials.monitor_and_details}
                    position={[1.187, -0.184, 1.391]}
                    rotation={[-0.062, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_209.geometry}
                    material={materials.monitor_and_details}
                    position={[2.815, -2.046, 0.018]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_211.geometry}
                    material={materials.monitor_and_details}
                    position={[2.815, -2.06, 0.018]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_213.geometry}
                    material={materials.monitor_and_details}
                    position={[1.587, -0.053, 0.001]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_215.geometry}
                    material={materials.monitor_and_details}
                    position={[1.587, -0.053, 0.001]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_217.geometry}
                    material={materials.monitor_and_details}
                    position={[1.587, -0.053, 0.001]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.big_details}
                    position={[-1.086, 1.254, -2.43]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials.big_details}
                    position={[-1.086, 0.445, -2.43]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials.big_details}
                    position={[-1.086, -0.358, -2.43]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_171.geometry}
                    material={materials.drivers}
                    position={[-0.194, 0.626, 2.827]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.big_details}
                    position={[-2.856, 0.733, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_173.geometry}
                    material={materials.drivers}
                    position={[-0.194, 1.002, 2.827]}
                />

                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials.big_details}
                    position={[-0.8, -0.491, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.big_details}
                    position={[-0.8, -0.53, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_219.geometry}
                    material={materials.monitor_and_details}
                    position={[-2.309, 0.931, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_75.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.75, 1.67, -2.802]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_97.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.75, 0.867, -2.802]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_99.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.75, 0.057, -2.802]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_101.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.298, 0.467, -0.497]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_113.geometry}
                    material={materials.material}
                    position={[-8.188, 3.567, 5.409]}
                    scale={0.035}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_115.geometry}
                    material={materials.material}
                    position={[-8.571, 5.687, 2.384]}
                    scale={0.065}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_117.geometry}
                    material={materials.material}
                    position={[-4.569, 3.792, -4.262]}
                    scale={0.065}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_119.geometry}
                    material={materials.material}
                    position={[-1.278, 2.238, 5.057]}
                    scale={0.016}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_121.geometry}
                    material={materials.material}
                    position={[-4.518, 1.438, -7.119]}
                    scale={0.019}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_123.geometry}
                    material={materials.material}
                    position={[-4.553, 3.611, -4.356]}
                    scale={0.024}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_125.geometry}
                    material={materials.material}
                    position={[-4.543, 3.44, -4.135]}
                    scale={0.024}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_127.geometry}
                    material={materials.material}
                    position={[-6.579, 4.96, -3.889]}
                    scale={0.024}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_129.geometry}
                    material={materials.material}
                    position={[-6.041, 2.714, 5.733]}
                    scale={0.035}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_131.geometry}
                    material={materials.material}
                    position={[-6.117, 2.84, 5.89]}
                    scale={0.015}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_133.geometry}
                    material={materials.material}
                    position={[-6.225, 2.442, 4.555]}
                    scale={0.015}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_135.geometry}
                    material={materials.material}
                    position={[-6.978, 2.442, 0.001]}
                    scale={0.019}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_137.geometry}
                    material={materials.material}
                    position={[-8.356, 7.664, -2.234]}
                    scale={0.054}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_139.geometry}
                    material={materials.material}
                    position={[-8.234, 7.21, -1.99]}
                    scale={0.028}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_146.geometry}
                    material={materials.drivers}
                    position={[-0.306, 0.745, 2.835]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_187.geometry}
                    material={materials.glass}
                    position={[-1.278, 0.745, 2.835]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_151.geometry}
                    material={materials.drivers}
                    position={[-1.012, 0.745, 2.835]}
                    rotation={[-Math.PI / 4, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_153.geometry}
                    material={materials.drivers}
                    position={[-0.194, 0.239, 2.827]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_189.geometry}
                    material={materials.glass}
                    position={[-0.404, 0.745, 2.835]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.big_details}
                    position={[-1.086, 1.254, 2.472]}
                    rotation={[Math.PI, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_155.geometry}
                    material={materials.drivers}
                    position={[-0.205, -0.841, 2.829]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.big_details}
                    position={[-1.086, -0.351, 2.472]}
                    rotation={[Math.PI, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_157.geometry}
                    material={materials.drivers}
                    position={[0.393, -0.457, 2.603]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_159.geometry}
                    material={materials.drivers}
                    position={[0.086, -0.513, 3.435]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_203.geometry}
                    material={materials.monitor_and_details}
                    position={[1.015, -0.175, 0.001]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_223.geometry}
                    material={materials.monitor_and_details}
                    position={[2.185, -1.011, 0.688]}
                    rotation={[0, 0, -1.404]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_225.geometry}
                    material={materials.monitor_and_details}
                    position={[2.176, -1.02, -0.577]}
                    rotation={[0, 0, -1.408]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_227.geometry}
                    material={materials.monitor_and_details}
                    position={[2.176, -1.02, -0.643]}
                    rotation={[0, 0, -1.408]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_229.geometry}
                    material={materials.monitor_and_details}
                    position={[1.587, -0.053, 0.001]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_231.geometry}
                    material={materials.monitor_and_details}
                    position={[-2.405, 0.931, 0]}
                    rotation={[0, 0, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_161.geometry}
                    material={materials.drivers}
                    position={[-0.089, 0.335, 2.835]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_163.geometry}
                    material={materials.drivers}
                    position={[-0.286, -0.083, 2.861]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_103.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -2.948, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_105.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -2.948, 0]}
                    rotation={[0, Math.PI / 3, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_107.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -2.948, 0]}
                    rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_109.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -2.948, 0]}
                    rotation={[Math.PI, 0, Math.PI]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_77.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -2.948, 0]}
                    rotation={[Math.PI, -Math.PI / 3, Math.PI]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_111.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -2.948, 0]}
                    rotation={[0, -Math.PI / 3, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.big_details}
                    position={[-0.8, -0.579, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_79.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -0.591, 0]}
                    rotation={[0, 0, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials.big_details}
                    position={[-0.8, -0.785, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_221.geometry}
                    material={materials.monitor_and_details}
                    position={[2.185, -1.011, 0.886]}
                    rotation={[0, 0, -1.404]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_283.geometry}
                    material={materials.keyboard}
                    position={[2.673, -1.385, -0.853]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_81.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.8, -0.579, 0]}
                />
                <Float speed={3}
                       rotationIntensity={0}
                       floatIntensity={3}
                       floatingRange={[0,0.25]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_193.geometry}
                            material={materials.floor}
                            position={[-4.851, 6.216, -0.251]}
                            rotation={[0, 0.166, 0]}
                            scale={0.006}
                        />
                </Float>


                <Float speed={3}
                       rotationIntensity={0}
                       floatIntensity={3}
                       floatingRange={[0, 0.25]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_191.geometry}
                            material={materials.floor}
                            position={[-6.245, 6.216, 0.17]}
                            scale={0.006}
                        />
                </Float>



                <Float speed={3}
                       rotationIntensity={0}
                       floatIntensity={3}
                       floatingRange={[0, 0.25]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_199.geometry}
                            material={materials.floor}
                            position={[-6.653, 6.392, 0.081]}
                            rotation={[-Math.PI / 2, -1.197, -Math.PI / 2]}
                            scale={[5.5, 5.099, 5.099]}
                            material-color={isChatbotAngry ? 'red': 'green'}
                        />
                </Float>

                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_85.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.931, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_87.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.114, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_83.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.931, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials.big_details}
                    position={[-0.8, 2.716, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.big_details}
                    position={[-0.8, 2.649, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_185.geometry}
                    material={materials.glass}
                    position={[-0.8, 2.709, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_91.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-0.303, -0.54, 2.149]}
                    rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_93.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.354, 0.589, 0.462]}
                    rotation={[-Math.PI, 0, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_89.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.931, 0]}
                    rotation={[0, 0, -2.142]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_95.geometry}
                    material={materials.Cable_and_conectors}
                    position={[-2.26, 0.931, 0]}
                    rotation={[0, 0, -2.142]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_271.geometry}
                    material={materials.keyboard}
                    position={[3.111, -1.422, 0.049]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_275.geometry}
                    material={materials.keyboard}
                    position={[2.816, -1.394, 0.969]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_277.geometry}
                    material={materials.keyboard}
                    position={[2.966, -1.405, 0.939]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_279.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.408, -0.997]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_281.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.408, -0.753]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_273.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.997]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_235.geometry}
                    material={materials.monitor_and_details}
                    position={[-2.329, 0.931, 0]}
                    rotation={[0, 0, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_237.geometry}
                    material={materials.numbers}
                    position={[-6.442, 3.567, 2.294]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_239.geometry}
                    material={materials.numbers}
                    position={[-7.091, 5.523, -2.53]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={0.418}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_241.geometry}
                    material={materials.numbers}
                    position={[-5.518, 3.567, 3.969]}
                    rotation={[0, 0.647, -Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_243.geometry}
                    material={materials.numbers}
                    position={[-1.116, 2.412, -5.797]}
                    rotation={[0, -1.103, -Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_245.geometry}
                    material={materials.numbers}
                    position={[-1.151, 3.567, 6.242]}
                    rotation={[-Math.PI, 1.197, Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_247.geometry}
                    material={materials.numbers}
                    position={[-6.055, 3.567, -3.443]}
                    rotation={[0, -0.684, -Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_249.geometry}
                    material={materials.numbers}
                    position={[-5.956, 2.382, 3.257]}
                    rotation={[0, 0.336, -Math.PI / 2]}
                    scale={0.173}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_251.geometry}
                    material={materials.numbers}
                    position={[-2.814, 3.176, 6.487]}
                    rotation={[-3.142, 1.553, Math.PI / 2]}
                    scale={0.289}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_253.geometry}
                    material={materials.numbers}
                    position={[-6.023, 4.835, 5.973]}
                    rotation={[0, 0.926, -Math.PI / 2]}
                    scale={0.471}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_255.geometry}
                    material={materials.numbers}
                    position={[-6.018, 6.409, 3.168]}
                    rotation={[0, 0.336, -Math.PI / 2]}
                    scale={0.417}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_257.geometry}
                    material={materials.numbers}
                    position={[-5.851, 2.232, -5.228]}
                    rotation={[0, -0.812, -Math.PI / 2]}
                    scale={0.38}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_259.geometry}
                    material={materials.numbers}
                    position={[-6.167, 5.213, -5.127]}
                    rotation={[0, -0.594, -Math.PI / 2]}
                    scale={0.409}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_261.geometry}
                    material={materials.numbers}
                    position={[-0.22, 1.818, 3.841]}
                    rotation={[0, 1.504, -Math.PI / 2]}
                    scale={0.223}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_263.geometry}
                    material={materials.numbers}
                    position={[-1.371, 0.685, -3.925]}
                    rotation={[0, -1.396, -Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_265.geometry}
                    material={materials.numbers}
                    position={[-6.236, 2.312, -0.697]}
                    rotation={[0, -0.142, -Math.PI / 2]}
                    scale={0.327}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_267.geometry}
                    material={materials.numbers}
                    position={[-6.378, 1.814, 1.134]}
                    rotation={[0, -0.044, -Math.PI / 2]}
                    scale={0.266}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_269.geometry}
                    material={materials.numbers}
                    position={[-3.706, 2.891, -6.001]}
                    rotation={[0, -1.197, -Math.PI / 2]}
                    scale={0.189}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_165.geometry}
                    material={materials.drivers}
                    position={[0.494, -0.485, 2.605]}
                    rotation={[0, 0, -Math.PI / 2]}
                />

                {/* Screen */}
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_233.geometry}
                    position={[1.587, -0.053, 0.001]}
                    rotation={[0, 0, -1.444]}
                    material-color={'#051e11'}

                >

                        <Html scale={[0.29,0.14,0.2]} rotation={[Math.PI / 2 ,Math.PI  ,Math.PI * 1.5]}  position={[0, 0.2948, 0.002]} fullscreen={true} occlude={true}  transform>
                            <ApolloProvider client={client}>
                                <Chat isChatbotAngry={isChatbotAngry} setIsChatbotAngry={setIsChatbotAngry} />

                            </ApolloProvider>


                        </Html>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials.big_details}
                    position={[-0.8, -2.948, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_169.geometry}
                    material={materials.drivers}
                    position={[0.503, -0.455, 3.009]}
                    rotation={[Math.PI / 2, 1.347, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_167.geometry}
                    material={materials.drivers}
                    position={[0.503, -0.455, 3.199]}
                    rotation={[Math.PI / 2, 1.347, -Math.PI / 2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_329.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.896]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_331.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.758]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_333.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.62]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_335.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.482]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_337.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.344]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_339.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.207]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_341.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 0.069]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_343.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.069]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_345.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.207]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_347.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.345]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_349.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.483]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_351.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.62]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_353.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.758]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_355.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -0.896]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_357.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, -1.034]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_359.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.823]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_361.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.685]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_363.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.548]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_365.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.41]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_367.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.272]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_369.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, 0.134]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_371.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -0.004]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_373.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -0.142]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_375.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -0.279]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_377.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -0.417]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_379.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -0.555]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_381.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -0.693]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_385.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, 0.765]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_387.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, 0.627]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_383.geometry}
                    material={materials.keyboard}
                    position={[2.672, -1.379, -1.032]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_389.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, 0.489]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_391.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, 0.351]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_393.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, 0.214]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_395.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, 0.076]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_397.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, -0.062]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_399.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, -0.2]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_401.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, -0.338]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_403.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, -0.476]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_405.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, -0.613]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_407.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, 0.696]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_409.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, 0.558]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_411.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, 0.421]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_413.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, 0.283]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_415.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, 0.145]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_417.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, 0.007]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_419.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, -0.131]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_421.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, -0.269]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_423.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, -0.406]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_425.geometry}
                    material={materials.keyboard}
                    position={[2.965, -1.393, -0.544]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_427.geometry}
                    material={materials.keyboard}
                    position={[2.817, -1.393, -1.034]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_327.geometry}
                    material={materials.keyboard}
                    position={[2.527, -1.368, 1.034]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials.big_details}
                    position={[-0.8, -0.717, 0]}
                />
        </group>
    )
}

useGLTF.preload('/models/scifi-computer.glb')
