apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: chatbot-helper-frontend
          image: johnnymacarroni95/chatbot-helper-frontend:latest
          ports:
            - containerPort: 80
