trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      inputs: 
        versionSpec: '16.19.0'
      displayName: Install NodeJS

    - script: |
        echo "Current working directory:"
        pwd
        echo "Listing root directory contents:"
        ls -la
        cd "frontend"
        echo "Listing frontend directory contents:"
        ls -la
        echo "Printing package.json contents:"
        cat package.json
      displayName: 'Inspect frontend directory and package.json'

    - script: npm install
      displayName: Install dependencies

    - script: |
        ls -la
        cat package.json 
      displayName: Change directory to frontend

    - script: npm run lint
      displayName: Run lint

    - script: npm run build
      displayName: Create build

