trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

stages:
- stage: Build
  displayName: Build frontend
  jobs:
  - job: Build
    displayName: Build frontend

    steps:
    - task: UseNode@1
      inputs: 
        versionSpec: '16.x'
      displayName: Install NodeJS

    - script: cd frontend
      displayName: Change directory to frontend

    - script: |
      npm install
      displayName: Install dependencies

    - script: |
      npm run lint
      displayName: Run lint

    - script: |
      npm run build
      displayName: Create build

