trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

variables:
  frontendPath: frontend
  buildOutputPath: build

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      displayName: Install NodeJS
      inputs:
        version: 18.17.0

    - task: Npm@1
      displayName: Install dependencies
      inputs:
        command: custom
        customCommand: install -D vite
        workingDir:  $(frontendPath)

    - task: Npm@1
      inputs:
        command: custom
        customCommand: run lint
        workingDir: $(frontendPath)
      displayName: Run lint

    - task: Npm@1
      displayName: Run build
      inputs:
        command: custom
        customCommand: run build
        workingDir: $(frontendPath)

    - task: CopyFiles@2
      displayName: Copy build output to artifact directory
      inputs:
        SourceFolder: $(frontendPath)
        Contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)/$(buildOutputPath)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)/$(buildOutputPath)
        ArtifactName: frontend-build-artifact
      displayName: Publish build artifacts
      
  