trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

variables:
  frontendPath: 'frontend'

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      displayName: Install NodeJS
      inputs:
        version: '18.17.0'

    - task: Npm@1
      displayName: Install dependencies

      inputs:
        command: 'custom'
        customCommand: 'npm install -D vite'
        workingDir: ${frontendPath}

    - task: Npm@1
      displayName: 'Run lint'
      inputs:
        command: 'custom'
        customComand: 'npm run lint'
        workingDir: ${frontendPath}

    - task: Npm@1
      displayName: 'Run build'
      inputs:
        command: 'custom'
        customCommand: 'npm run build'
        workingDir: ${frontendPath}