trigger:
- dev

resources:
- repo: self

variables:
  frontendPath: 'frontend'

pool: self-hosted-pool

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      inputs:
        version: '18.17.0'
      displayName: Install NodeJS

    - script: |
        cd ${frontendPath}
        npm install
      displayName: Install dependencies

    - script: |
        cd frontend
        npm run lint
      displayName: Run lint

    - script: | 
        cd ${frontendPath}
        npm run build
      displayName: Create build