trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      inputs: 
        versionSpec: '16.19.0'
      displayName: Install NodeJS

    - script: cd frontend
      displayName: Change directory to frontend

    - script: npm install
      displayName: Install dependencies

    - script: |
      ls -la
      cat package.json 
      displayName: Change directory to frontend

    - script: npm run lint
      displayName: Run lint

    - script: npm run build
      displayName: Create build

