trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

variables:
  type: frontend
  frontendFolder: frontend
  buildOutputPath: build

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    
    - template: build-template.yml
      parameters:
        type: $(type)
        workingDir: $(frontendFolder)
        buildOutputPath: $(buildOutputPath)
