trigger:
- dev

resources:
- repo: self

pool: self-hosted-pool

variables:
  frontendPath: frontend
  buildOutputPath: build

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      displayName: Install NodeJS
      inputs:
        version: 18.17.0
    
    - template: frontend-build-template.yml
      parameters:
        workingDir: $(frontendPath)
        buildOutputPath: $(buildOutputPath)
