trigger:
- dev

resources:
- repo: self

variables:
  frontendPath: 'frontend'

pool: self-hosted-pool

stages:
- stage: Build
  displayName: Build frontend stage
  jobs:
  - job: Build
    displayName: Build frontend job

    steps:
    - task: UseNode@1
      inputs:
        version: '18.17.0'
      displayName: Install NodeJS

    - script: npm install -D vite
      displayName: Install dependencies
      workingDirectory: ${frontendPath}

    - script: npm run lint
      displayName: Run lint
      workingDirectory: ${frontendPath}

    - script: npm run build
      displayName: Create build
      workingDirectory: ${frontendPath}
